/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.yanopuedomas;

import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import javax.swing.JOptionPane;
import org.bson.Document;
/**
 *
 * @author Demera
 */
public class Payment extends javax.swing.JFrame {
    private final InsertPayment funciones;
    private final SaveJSON save;
    private final ValidationPAY validation;
     private final EditPaymentDetails edit;
    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();
        funciones = new InsertPayment();
        save = new SaveJSON();
        edit = new EditPaymentDetails();
        validation = ValidationPAY.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        date = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nameCard = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cardNumber = new javax.swing.JTextField();
        expiration = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cvv = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        pay = new javax.swing.JButton();
        clean = new javax.swing.JButton();
        Modify = new javax.swing.JButton();
        cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 36, -1, -1));
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 58, 120, -1));

        jLabel3.setText("Cedula");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 36, -1, -1));

        Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdActionPerformed(evt);
            }
        });
        getContentPane().add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 58, 71, -1));

        jLabel2.setText("Direccion");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 130, -1));
        getContentPane().add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 120, -1));

        jLabel4.setText("Telefono");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 90, -1));

        jLabel5.setText("Correo");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 140, -1));

        jLabel6.setText("Fecha de Nacimiento");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 130, -1));

        jLabel7.setText("Pago tarjeta");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 249, -1, -1));

        jLabel8.setText("Titular de la tarjeta");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 277, -1, -1));
        getContentPane().add(nameCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 140, -1));

        jLabel9.setText("Numero de tarjeta");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));
        getContentPane().add(cardNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 140, -1));
        getContentPane().add(expiration, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 140, -1));

        jLabel10.setText("Fecha expiración");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        jLabel11.setText("CVV");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));
        getContentPane().add(cvv, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 140, -1));

        jLabel12.setText("Pago Total");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        pay.setText("PAGAR");
        pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payActionPerformed(evt);
            }
        });
        getContentPane().add(pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, -1));

        clean.setText("Limpiar campos");
        clean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanActionPerformed(evt);
            }
        });
        getContentPane().add(clean, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, -1, 20));

        Modify.setText("Modificar Datos");
        Modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyActionPerformed(evt);
            }
        });
        getContentPane().add(Modify, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, -1, -1));

        cancel.setText("Cancelar Compra");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdActionPerformed

    private void payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payActionPerformed
        // TODO add your handling code here:
        ValidationPAY validation = ValidationPAY.getInstance();
        // Se crea una instancia de la estrategia PDFInvoiceStrategy
        PDFInvoice pdf = new PDFInvoice();
        // Se instancia la clase SavePDF
        SavePDF savePDF = new SavePDF();
        if (Name.getText().isEmpty() || Id.getText().isEmpty() || address.getText().isEmpty() ||
            phone.getText().isEmpty() || email.getText().isEmpty() || date.getDate() == null ||
            nameCard.getText().isEmpty() || cardNumber.getText().isEmpty() || 
            expiration.getText().isEmpty() || cvv.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Debe llenar todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
        return;
        }
        //Se llama a la instancia y al metodo validateName
        if (!validation.validateName(Name.getText())) {
        JOptionPane.showMessageDialog(this, "Ingrese un nombre válido", "Error", JOptionPane.ERROR_MESSAGE);
        return;
        }
        if (!validation.validateID(Id.getText())) {
            JOptionPane.showMessageDialog(this, "Ingrese una cedula correcta", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!validation.validatePhone(phone .getText())) {
            JOptionPane.showMessageDialog(this, "Ingrese un numero de telefono valido (09)", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!validation.validateEmail(email.getText())) {
            JOptionPane.showMessageDialog(this, "Ingrese un email valido", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(!validation.validateFullName(nameCard.getText())){
            JOptionPane.showMessageDialog(this,"Ingrese sus dos nombres y dos apellidos","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!validation.validateCreditCard(cardNumber.getText())) {
            JOptionPane.showMessageDialog(this, "Ingrese un numero de tarjeta valido", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!validation.validateExpirationDate(expiration.getText())) {
            JOptionPane.showMessageDialog(this, "ingrese una fecha de expiracion correcta", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
       
        if (!validation.validateCVV(cvv.getText())) {
            JOptionPane.showMessageDialog(this, "Ingrese un numero de CVV valido", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        funciones.InsertarPago(Name.getText(), Id.getText(), address.getText(), phone.getText(), email.getText(), expiration.getText(), nameCard.getText(), cardNumber.getText(), cvv.getText());
        save.InsertarPagoJSON(Name.getText(), Id.getText(), address.getText(), phone.getText(), email.getText(), expiration.getText(), nameCard.getText(), cardNumber.getText(), cvv.getText());
        savePDF.setInvoiceGeneration(pdf);
        JOptionPane.showMessageDialog(this, "Pago exitoso. Datos guardados en MongoDB y en un archivo JSON", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_payActionPerformed

    private void cleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanActionPerformed
        // TODO add your handling code here:
        Name.setText("");
        Id.setText("");
        address.setText("");
        cardNumber.setText("");
        email.setText("");
        expiration.setText("");
        cvv.setText("");
        nameCard.setText("");
        phone.setText("");
        date.setDate(null);
        JOptionPane.showMessageDialog(this,"Los campos se han limpiado","Exito",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_cleanActionPerformed

    private void ModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyActionPerformed
        // TODO add your handling code here:
      String ID = JOptionPane.showInputDialog(this, "Ingrese la Cedula de la factura que desea modificar:", "Modificar Factura", JOptionPane.QUESTION_MESSAGE);
    if (ID != null && !ID.isEmpty()) {
        String newID = JOptionPane.showInputDialog(this, "Ingrese el nueva cedula:", "Modificar Factura", JOptionPane.QUESTION_MESSAGE);
        String name = JOptionPane.showInputDialog(this, "Ingrese el nuevo nombre:", "Modificar Factura", JOptionPane.QUESTION_MESSAGE);
        String address = JOptionPane.showInputDialog(this, "Ingrese la nueva dirección:", "Modificar Factura", JOptionPane.QUESTION_MESSAGE);
        String phone = JOptionPane.showInputDialog(this, "Ingrese el nuevo teléfono:", "Modificar Factura", JOptionPane.QUESTION_MESSAGE);
        String email = JOptionPane.showInputDialog(this, "Ingrese el nuevo correo electrónico:", "Modificar Factura", JOptionPane.QUESTION_MESSAGE);
        
        // Llamar al método para modificar la factura
        edit.EditPay(ID, newID, name, address, phone, email);
    }
    }//GEN-LAST:event_ModifyActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        int confirmacion = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea cancelar su compra?", "Confirmar cancelación", JOptionPane.YES_NO_OPTION);
        if (confirmacion == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "Compra cancelada", "Cancelación exitosa", JOptionPane.INFORMATION_MESSAGE);
            
        }
        Inter1 inter = new Inter1();
        inter.setVisible(true);
        inter.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Id;
    private javax.swing.JButton Modify;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField address;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField cardNumber;
    private javax.swing.JButton clean;
    private javax.swing.JTextField cvv;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JTextField email;
    private javax.swing.JTextField expiration;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nameCard;
    private javax.swing.JButton pay;
    private javax.swing.JTextField phone;
    // End of variables declaration//GEN-END:variables
}
